CREATE TABLE IF NOT EXISTS "users" (
    "ID" SERIAL PRIMARY KEY,
    "USERNAME" VARCHAR(255) NOT NULL UNIQUE,
    "PASSWORD_HASH" VARCHAR(255) NOT NULL,
    "EMAIl" VARCHAR(255) NOT NULL UNIQUE,
    "FIRST_NAME" VARCHAR(255) NOT NULL,
    "LAST_NAME" VARCHAR(255) NOT NULL,
    "ROLE" VARCHAR(10) NOT NULL
);